# This docker compose file is used only to manage containers in development environment
version: '3.7'

services:
  transactions-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - transactions-db

  transactions-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE='clean-arch'
      - MYSQL_USER='clean-arch-user'
      - MYSQL_PASSWORD='clean-arch-pwd'
      - MYSQL_ROOT_PASSWORD='clean-arch-pwd-root'
    ports:
      - "3306:3306"